# This is everything required for the base infrastructure
base:
  - 'infra-monitoring'
  - 'infra-vpc'
  - 'infra-networking'
  - 'infra-root-dns-zones'
  - 'infra-stack-dns-zones'
  - 'infra-security-groups'
  - 'infra-database-backups-bucket'
  - 'infra-artefact-bucket'

# Management services
management:
  - 'app-docker-management'
  - 'app-graphite'
  - 'app-monitoring'

# Supporting services
support:
  # Enable access to the environment
  - 'app-jumpbox'
  # app-apt should be deployed for Gemstash
  - 'app-apt'
  - 'app-mirrorer'

# Datastores
datastores:
  - 'app-backend-redis'
  - 'app-db-admin'
  - 'app-mongo'
  - 'app-mysql'
  - 'app-postgresql'
  - 'app-rabbitmq'
  - 'app-router-backend'
  - 'app-rummager-elasticsearch'
  - 'app-transition-db-admin'
  - 'app-transition-postgresql'

# Cache
cache:
  - 'app-cache'
  - 'app-draft-cache'

# Core applications
core:
  - 'app-publishing-api'
  - 'app-content-store'
  - 'app-draft-content-store'
  - 'app-search'

# Frontend applications
frontend:
  - 'app-calculators-frontend'
  - 'app-draft-frontend'
  - 'app-frontend'
  - 'app-bouncer'
  - 'app-whitehall-frontend'

# Backend applications
backend:
  - 'app-asset-master'
  - 'app-backend'
  - 'app-email-alert-api'
  - 'app-mapit'
  - 'app-whitehall-backend'

# These load balancers have a dependency on all applications
public:
  - 'infra-public-services'

# Anything with an EC2 instance except snowflakes. This is ordered
# to ensure application groups are deployed last, particularly the ones
# that deploy most apps, like app-backend.
all_node_groups:
  - 'app-jumpbox'
  - 'app-apt'
  - 'app-mirrorer'
  - 'app-db-admin'
  - 'app-transition-db-admin'
  - 'app-docker-management'
  - 'app-monitoring'
  - 'app-graphite'
  - 'app-rabbitmq'
  - 'app-rummager-elasticsearch'
  - 'app-mongo'
  - 'app-router-backend'
  - 'app-cache'
  - 'app-draft-cache'
  - 'app-publishing-api'
  - 'app-search'
  - 'app-content-store'
  - 'app-draft-content-store'
  - 'app-email-alert-api'
  - 'app-asset-master'
  - 'app-bouncer'
  - 'app-mapit'
  - 'app-whitehall-backend'
  - 'app-whitehall-frontend'
  - 'app-calculators-frontend'
  - 'app-draft-frontend'
  - 'app-frontend'
  - 'app-backend'
