#!/bin/bash
#
# Snippet: base
#

echo "[$(date '+%H:%M:%S %d-%m-%Y')] START SNIPPET: base"

# Source DISTRIB_* env vars
# shellcheck disable=SC1091
. /etc/lsb-release

export DEBIAN_FRONTEND=noninteractive

echo "[$(date '+%H:%M:%S %d-%m-%Y')] base: configure locales ..."
echo "LC_ALL=en_GB.UTF-8" > /etc/environment
locale-gen "en_GB.UTF-8"
dpkg-reconfigure locales

echo "[$(date '+%H:%M:%S %d-%m-%Y')] base: regenerate the servers hosts keys to ensure they are unique ..."
rm -f /etc/ssh/ssh_host*key*
dpkg-reconfigure openssh-server

echo "[$(date '+%H:%M:%S %d-%m-%Y')] base: install Puppet repository ..."
TMPFILE=$(mktemp)
wget -qO $TMPFILE http://apt.puppetlabs.com/puppetlabs-release-$DISTRIB_CODENAME.deb
dpkg -i $TMPFILE
rm $TMPFILE

echo "[$(date '+%H:%M:%S %d-%m-%Y')] base: install Gov.UK package signing key and repositories ..."
curl --silent --show-error --fail \
  https://apt.publishing.service.gov.uk/EC5FE1A937E3ACBB.asc | apt-key add -

echo "deb [arch=amd64] http://apt.production.alphagov.co.uk/awscli $DISTRIB_CODENAME main" \
  >> /etc/apt/sources.list.d/awscli.list

echo "[$(date '+%H:%M:%S %d-%m-%Y')] base: ensure the packages are up to date ..."
apt-get update -qq
apt-get -y upgrade

echo "[$(date '+%H:%M:%S %d-%m-%Y')] base: install AWS cli ..."
apt-get install -y awscli jq

echo "[$(date '+%H:%M:%S %d-%m-%Y')] base: install LVM ..."
apt-get install -y lvm2

echo "[$(date '+%H:%M:%S %d-%m-%Y')] base: generate local facts ..."
INSTANCE_ID=$(ec2metadata --instance-id)
REGION=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | grep region | awk -F\" '{print $4}')
TAGS=$(aws ec2 describe-tags --filters "Name=resource-id,Values=$INSTANCE_ID" "Name=tag-key,Values=aws_*" --region=$REGION --output=json | jq -r '.Tags[] | [.Key, .Value] | @csv' | tr -d '"')

mkdir -p /etc/facter/facts.d/

for I in $TAGS
do
  KEY=$(echo $I | cut -d"," -f1)
  VALUE=$(echo $I | cut -d"," -f2)
  echo $KEY=$VALUE > /etc/facter/facts.d/$KEY.txt
done

echo "[$(date '+%H:%M:%S %d-%m-%Y')] base: install Puppet ..."
apt-get -y install make ruby1.9.3 puppet='3.8.*' puppet-common='3.8.*'
service puppet stop

echo "[$(date '+%H:%M:%S %d-%m-%Y')] base: add search domains ..."
F_AWS_ENVIRONMENT=$(facter aws_environment)
if [[ -z $F_AWS_ENVIRONMENT ]] ; then
  echo "ERROR aws_environment is null"
else
  echo "append domain-search \"${F_AWS_ENVIRONMENT}.govuk-internal.digital\", \"govuk-internal.digital\";" >> /etc/dhcp/dhclient.conf
  dhclient -r; dhclient
  echo "search ${F_AWS_ENVIRONMENT}.govuk-internal.digital govuk-internal.digital" >> /etc/resolvconf/resolv.conf.d/base
fi

echo "[$(date '+%H:%M:%S %d-%m-%Y')] END SNIPPET: base"

