/*
* ## Module: shared_scrubbed_snapshot_finder
*
* This module queries RDS for shared snapshots generated by the
* govuk-datascrubber and reports back their ARNs.
*/

variable "enable" {
  type        = "string"
  description = "Whether to run resources in the module or not (0 or 1)"

  default = "1"
}

variable "source_db_engine" {
  type        = "string"
  description = "The engine of the source database (mysql or postgresql)"
}

variable "source_db_instance_identifier" {
  type        = "string"
  description = "The instance identifier of the original RDS DB instance that the scrubbed snapshot came from"
}

# Locals
#--------------------------------------------------------------

locals {
  db_instance_identifier = "scrubber-${var.source_db_engine}-${substr(sha256(var.source_db_instance_identifier), 0, 12)}"
}

# Resources
#--------------------------------------------------------------

# Disabled with count=0 until bug in AWS provider is resolved:
# https://github.com/terraform-providers/terraform-provider-aws/issues/3907
data "aws_db_snapshot" "scrubbed" {
  count                  = 0
  db_instance_identifier = "${local.db_instance_identifier}"
  snapshot_type          = "shared"
  include_shared         = true
  most_recent            = true
}

# This is the workaround
data "external" "shared_snapshot_query" {
  program = ["${path.module}/shared_snapshot_query.sh"]

  query = {
    enable                 = "${var.enable}"
    db_instance_identifier = "${local.db_instance_identifier}"
  }
}

# Outputs
#--------------------------------------------------------------

output "snapshot_arn" {
  value = "${var.enable == 0 ? "" : lookup(data.external.shared_snapshot_query.result, "arn")}"
}
