#!/bin/bash
ENVIRONMENT=$1
STACKNAME=$2
PUPPET_ROLE=$3

function usage() {
  echo "Usage: "
  echo "govuk-ssh <integration> <stackname> <puppet_role or IP>"
  exit 1
}

if [[ $STACKNAME == "" ]] || [[ $PUPPET_ROLE == "" ]] || [[ $ENVIRONMENT == "" ]]; then
  usage
fi

# SSH to specific machine if IP is specified
if [[ $PUPPET_ROLE =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
  ssh -tA jumpbox.$STACKNAME.$ENVIRONMENT.govuk.digital "ssh ${PUPPET_ROLE}"
else
  # Otherwise hop to a machine for that puppet role
  ssh -tA jumpbox.$STACKNAME.$ENVIRONMENT.govuk.digital "ssh-proxy ${STACKNAME} ${PUPPET_ROLE}"
fi
