#!/bin/bash
#
# This is a wrapper for terraform to make running projects easier.
# It takes three arguments: the command (e.g. "init" or "apply"), the project
# name (e.g. "infra-networking" or "app-jumpbox") and the stack to run it in.
#

set -e

while getopts "c:d:e:p:s:r:h" option
do
  case $option in
    c ) CMD=$OPTARG ;;
    d ) DATA_DIR=$OPTARG ;;
    e ) ENVIRONMENT=$OPTARG ;;
    p ) PROJECT=$OPTARG ;;
    r ) GOVUK_AWS_REPO=$OPTARG ;;
    s ) STACKNAME=$OPTARG ;;
    h ) HELP=1 ;;
  esac
done

function usage() {
  cat <<EOM
usage: $0 -c -e -p -s

     -c   The Terraform command (CMD) to run, eg "plan", "apply" or "destroy".
     -d   The root of the data directory (DATA_DIR) to take .tfvars files from.
     -e   The ENVIRONMENT to deploy to eg "aws-integration".
     -s   Specify the STACKNAME of the ".tfvars" and ".backend" files.
     -r   Specify the GOVUK_AWS_REPO location (ie the root of this repository).
     -p   Specify which PROJECT to create, eg "infra-networking".
     -h   Display this message.

Any remaining arguments are passed to Terraform
e.g. $0 -c plan -e foo -p bar -s baz -- -var further=override
     will pass "-var further=override" to terraform

Tip: these arguments can be passed by environment variable as well
     using the upper case version of their name.
EOM
}

function log_error() {
  echo -e "ERROR: $*\n"
  HELP=1
}

if [[ $HELP = '1' ]]; then
  usage
  exit
fi

# un-shift all the parsed arguments
shift $(expr $OPTIND - 1)

# Unless we set the argument or env var, assume we're running this from the
# root of the project
if [[ -z $GOVUK_AWS_REPO ]]; then
  GOVUK_AWS_REPO=$(pwd)
fi

# Move to AWS repo to run commands
cd $GOVUK_AWS_REPO

# Set up our locations
TERRAFORM_DIR="${GOVUK_AWS_REPO}/terraform"

PROJECT_DIR="${TERRAFORM_DIR}/projects/${PROJECT}"
BACKEND_FILE="${ENVIRONMENT}.${STACKNAME}.backend"

# Make DATA_DIR path absolute so we can run script from anywhere
DATA_DIR="$(cd ${DATA_DIR} && pwd)"
echo "data dir is " $DATA_DIR

COMMON_DATA_DIR="${DATA_DIR}/common/${ENVIRONMENT}"

COMMON_DATA="${COMMON_DATA_DIR}/common.tfvars"
STACK_COMMON_DATA="${COMMON_DATA_DIR}/${STACKNAME}.tfvars"

PROJECT_DATA_DIR="${DATA_DIR}/${PROJECT}/${ENVIRONMENT}"

COMMON_PROJECT_DATA="${PROJECT_DATA_DIR}/common.tfvars"
SECRET_COMMON_PROJECT_DATA="${PROJECT_DATA_DIR}/common.secret.tfvars"
STACK_PROJECT_DATA="${PROJECT_DATA_DIR}/${STACKNAME}.tfvars"
SECRET_PROJECT_DATA="${PROJECT_DATA_DIR}/${STACKNAME}.secret.tfvars"

if [[ -z $(which terraform) ]]; then
  log_error 'Terraform not found, please make sure it is installed.'
fi

# Check we have all the arguments we need
if [[ -z $CMD ]];  then
  log_error 'Specify the Terraform command to run, eg "init", "plan" or "apply".'

fi

if [[ -z $PROJECT ]]; then
  log_error 'Specify which project to create, eg "infra-networking".'

elif [[ ! -d $PROJECT_DIR ]]; then
  log_error "Could not find $PROJECT directory: $PROJECT_DIR"

fi

if [[ -z $STACKNAME ]]; then
  log_error 'Specify the stackname (prefix of the ".tfvars" and ".backend" files).'

# We check for these files relative to $PROJECT_DIR as we'll later `cd` to them.
elif [[ $CMD == "init" ]] && [[ ! -f $PROJECT_DIR/$BACKEND_FILE ]]; then
  log_error "Could not find backend file '$PROJECT_DIR/$BACKEND_FILE'"

# e.g. terraform/projects/app-foo/../../data/app-foo/
elif [[ ! -f $STACK_COMMON_DATA ]] && \
     [[ ! -f $STACK_PROJECT_DATA ]] && \
     [[ ! -f $SECRET_PROJECT_DATA ]] && \
     [[ ! -f $COMMON_DATA ]]  && \
     [[ ! -f $SECRET_COMMON_PROJECT_DATA ]]  && \
     [[ ! -f $COMMON_PROJECT_DATA ]]; then
  log_error 'Could not find any tfvar files. Looked for:\n' \
            "\t$STACK_COMMON_DATA \n " \
            "\t$STACK_PROJECT_DATA \n " \
            "\t$SECRET_PROJECT_DATA \n " \
            "\t$COMMON_DATA\n " \
            "\t$SECRET_COMMON_PROJECT_DATA\n " \
            "\t$COMMON_PROJECT_DATA"
fi

# If there's been an error print the usage & exit
if [[ $HELP == "1" ]]; then
  usage
  exit 1
fi

# Run everything from the appropriate project
cd "$PROJECT_DIR"



# Actually run the command
function init() {
  rm -rf .terraform && \
  rm -rf terraform.tfstate.backup && \
  terraform init \
            -backend-config "$BACKEND_FILE"
}

# Build the command to run
TO_RUN="init && terraform $CMD"
# Append which ever tfvar files exist
for TFVAR_FILE in "$COMMON_DATA" \
                  "$STACK_COMMON_DATA" \
                  "$COMMON_PROJECT_DATA" \
                  "$SECRET_COMMON_PROJECT_DATA" \
                  "$STACK_PROJECT_DATA" \
                  "$SECRET_PROJECT_DATA"
do
  if [[ -f $TFVAR_FILE ]] &&
     (
      [[ "$TFVAR_FILE" == "$SECRET_PROJECT_DATA" ]] ||
      [[ "$TFVAR_FILE" == "$SECRET_COMMON_PROJECT_DATA" ]]
     ) ; then
    TO_RUN="$TO_RUN -var-file <(sops -d $TFVAR_FILE)"
  elif [[ -f $TFVAR_FILE ]]; then
    TO_RUN="$TO_RUN -var-file $TFVAR_FILE"
  fi
done

eval "$TO_RUN $@"
